version: '3.2'
services:
    web:
        image: winzerhofwurst/webserver
        ports:
            - "8082:80"
        env_file: .env.dev
        volumes:
            - "$WIWU_ROOT:/var/www"
    database:
        volumes:
            - ./maria-dev:/var/lib/mysql
        ports:
            - "33061:3361"
