version: "3.2"
services:
    web:
        restart: always
    core:
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=wiwu"
            - "DB_USERNAME=wiwu"
            - "DB_PASSWORD=wiwu123"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "CACHE_DRIVER=redis"
            - "SESSION_DRIVER=redis"
        restart: always
    database:
        image: mariadb:10.0
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=wiwu"
            - "MYSQL_USER=wiwu"
            - "MYSQL_PASSWORD=wiwu123"
        restart: always
    cache:
        image: redis:3.0
        restart: always
    magento:
        image: alexcheng/magento2
        environment:
            - "MAGENTO_DEFAULT_CURRENCY=EUR"
            - "MAGENTO_TIMEZONE=Europe/Vienna"
        volumes:
            - "magento-data:/var/www/html"
        restart: always
    magento-db:
        image: mysql:5.6.43
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=magento"
            - "MYSQL_USER=magento"
            - "MYSQL_PASSWORD=magento123"
        volumes:
            - "magento-db-data:/var/lib/mysql"
        restart: always

volumes:
    magento-db-data:
    magento-data:
