version: '3.2'
services:
    web:
        links:
            - cache
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "DB_DATABASE=wiwu"
            - "DB_USERNAME=wiwu"
            - "DB_PASSWORD=wiwu123"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "CACHE_DRIVER=array"
            - "SESSION_DRIVER=file"
        restart: always
    database:
        image: mariadb:10.0
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=wiwu"
            - "MYSQL_USER=wiwu"
            - "MYSQL_PASSWORD=wiwu123"
        restart: always
    cache:
        image: redis:3.0
        restart: always

