version: '3.2'
services:
    web:
        image: winzerhofwurst/web:latest
        environment:
            - "CORE_URL=http://core:80"
        ports:
            - "8080:8080"
    core:
        image: winzerhofwurst/core:latest
        env_file: .env.prod
    database:
        volumes:
            - db-data:/var/lib/mysql
    magento:
        ports:
            - "8081:8080"

volumes:
    db-data:
