version: '3.2'
services:
    web:
        image: winzerhofwurst/web:latest
        ports:
            - "8080:8080"
        env_file: .env.prod
    database:
        volumes:
            - ./maria-prod:/var/lib/mysql

